/-
# Extraction: a realizing term for each derivation rule

Extraction recurses on the derivation, carrying the context as a list of
ambient-indexed realizer *families* (`Fam`); the transports of
`Transport.lean` turn each binder's single-ambient realizer into such a
family (`famOf`), which is what closes the ambient-mismatch gap
identified in STATUS.md.

Every rule has its own named combinator, listed in STATUS.md:

* `axC`, and tail-recursion for `wk`;
* `andIC`, `andE₁C`, `andE₂C` — pointwise pairing and projections;
* `orI₁C`, `orI₂C` — tagging; `orEC` — pointwise tag-split, rebuilding
  the hypothesis family from the payload at each ambient (so no
  cross-ambient tag-coherence invariant is ever needed);
* `impIC` — abstraction over the family of the bound realizer;
  `impEC` — application one ambient up;
* `botEC` — vacuous; `allIC` — abstraction reading the numeral from the
  argument; `allEC` — application at the numeral of the term's value;
* `indC` — the induction recursor: the type-indexed primitive recursion
  `indRecC` (the one combinator that *iterates* — the number of `app₁`
  steps is the numeral being realized), packaged by `allIC`;
* `eqDecC` — the decidable-equality tag; `axiomC` — the (contentless)
  realizer of the two successor axioms.

`derivBound` assigns each derivation the ambient level above which its
extracted family realizes the conclusion (`Soundness.lean`).
-/
import Realizability.Transport

namespace Realizability

open ContinuousFunctionals

/-- Ambient-indexed realizer families. -/
def Fam : Type :=
  (n : ℕ) → PureType (n + 1)

/-- The junk family (never consulted where it matters). -/
noncomputable def defaultFam : Fam :=
  fun n => defaultPT (n + 1)

/-- Context realization: each hypothesis' family realizes it above its
formula's level. -/
def CtxR (ρ : ℕ → ℕ) : List Formula → List Fam → Prop
  | [], _ => True
  | φ :: Γ, env => FR ρ φ (env.headD defaultFam) ∧ CtxR ρ Γ env.tail

/-! ## The named combinators, one per rule -/

/-- `ax`: project the head hypothesis. -/
noncomputable def axC (env : List Fam) : Fam :=
  env.headD defaultFam

/-- `andI`: pointwise pairing. -/
noncomputable def andIC (f g : Fam) : Fam :=
  fun n => pairPT (f n) (g n)

/-- `andE₁`: pointwise first projection. -/
noncomputable def andE₁C (f : Fam) : Fam :=
  fun n => fstPT (f n)

/-- `andE₂`: pointwise second projection. -/
noncomputable def andE₂C (f : Fam) : Fam :=
  fun n => sndPT (f n)

/-- `orI₁`: tag `0`. -/
noncomputable def orI₁C (f : Fam) : Fam :=
  fun n => pairPT (fun _ => (0 : ℕ)) (f n)

/-- `orI₂`: tag `1`. -/
noncomputable def orI₂C (f : Fam) : Fam :=
  fun n => pairPT (fun _ => (1 : ℕ)) (f n)

/-- `orE`: pointwise tag-split on the major premise; each branch rebuilds
its hypothesis family from the payload at the current ambient. -/
noncomputable def orEC (φ ψ : Formula) (d : Fam)
    (b₁ b₂ : Fam → Fam) : Fam :=
  fun n =>
    if fstPT (d n) (defaultPT n) = 0 then
      b₁ (famOf φ (sndPT (d n))) n
    else
      b₂ (famOf ψ (sndPT (d n))) n

/-- `impI`: abstraction over the family generated by the bound
realizer. -/
noncomputable def impIC (φ : Formula) (body : List Fam → Fam)
    (env : List Fam) : Fam :=
  fun n =>
    match n with
    | 0 => defaultPT 1
    | m + 1 => abs₁ (fun x => body (famOf φ x :: env) m)

/-- `impE`: application, major premise one ambient up. -/
noncomputable def impEC (f g : Fam) : Fam :=
  fun n => app₁ (f (n + 1)) (g n)

/-- `botE`: vacuous. -/
noncomputable def botEC : Fam :=
  defaultFam

/-- `allI`: abstraction reading the numeral off the argument. -/
noncomputable def allIC (bodyAt : ℕ → Fam) : Fam :=
  fun n =>
    match n with
    | 0 => defaultPT 1
    | m + 1 => abs₁ (fun z => bodyAt (z (defaultPT m)) m)

/-- `allE`: application at the numeral of the term's value. -/
noncomputable def allEC (f : Fam) (k : ℕ) : Fam :=
  fun n => app₁ (f (n + 1)) (natPT (n + 1) k)

/-- **The type-indexed primitive recursor at a fixed ambient `m`**
(rule `ind`): from the base realizer `a` and the step functional `b` —
the step family's ambient-`(m + 2)` member, whose `∀` clause consumes a
numeral and whose `→` clause then consumes an ambient-`m` realizer —
iterate `app₁` along the numeral:

    indRecC a b 0       = a
    indRecC a b (k + 1) = app₁ (app₁ b (natPT (m + 2) k)) (indRecC a b k)

Unlike every other combinator in this file, this one *iterates*: the
number of applications performed is the numeral being realized.  It is
genuine primitive recursion at the realizer's own type
`PureType (m + 1)` (the `Nat.rec` motive is the pure type, not `ℕ`),
stated once uniformly in the ambient `m` per the level-free-core
discipline — the ambient never changes during the iteration, because
`MR`'s `→` clause consumes and produces at the same level.  Correctness
is `MR_indRecC` in `Soundness.lean`. -/
noncomputable def indRecC {m : ℕ} (a : PureType (m + 1))
    (b : PureType (m + 3)) : ℕ → PureType (m + 1)
  | 0 => a
  | k + 1 => app₁ (app₁ b (natPT (m + 2) k)) (indRecC a b k)

/-- `ind`: the recursor family — combinator 17.  At each numeral `k`
the ambient-indexed family `m ↦ indRecC (a m) (b (m + 2)) k`, packaged
by `allIC` exactly as `∀`-introduction packages its uniform families:
the concluded formula has the same `∀x. φ` shape, so the same packaging
(abstraction reading the numeral off the argument) applies verbatim. -/
noncomputable def indC (a b : Fam) : Fam :=
  allIC fun k => fun m => indRecC (a m) (b (m + 2)) k

/-- `eqDec`: tag by the (meta-level) decision of the equation; the
payloads are contentless. -/
noncomputable def eqDecC (t : Bool) : Fam :=
  fun n =>
    if t then pairPT (fun _ => (0 : ℕ)) (defaultPT (n + 1))
    else pairPT (fun _ => (1 : ℕ)) (defaultPT (n + 1))

/-- `succNeZero` and `succInj` — and, since Phase A, the equational-logic
schemas and the recursion equations for `+`/`×`: contentless realizers
(their implication clauses are vacuous or carry a true equation). -/
noncomputable def axiomC : Fam :=
  defaultFam

/-! ## The extraction function -/

/-- **Extraction**: a realizing family for each derivation, by recursion
on the derivation, dispatching to the named combinators. -/
noncomputable def extract : {Γ : List Formula} → {φ : Formula} →
    Deriv Γ φ → (ℕ → ℕ) → List Fam → Fam
  | _, _, .ax, _, env => axC env
  | _, _, .wk D, ρ, env => extract D ρ env.tail
  | _, _, .andI D₁ D₂, ρ, env => andIC (extract D₁ ρ env) (extract D₂ ρ env)
  | _, _, .andE₁ D, ρ, env => andE₁C (extract D ρ env)
  | _, _, .andE₂ D, ρ, env => andE₂C (extract D ρ env)
  | _, _, .orI₁ D, ρ, env => orI₁C (extract D ρ env)
  | _, _, .orI₂ D, ρ, env => orI₂C (extract D ρ env)
  | _, _, @Deriv.orE _ φ ψ _ D D₁ D₂, ρ, env =>
      orEC φ ψ (extract D ρ env)
        (fun p => extract D₁ ρ (p :: env))
        (fun p => extract D₂ ρ (p :: env))
  | _, _, @Deriv.impI _ φ _ D, ρ, env =>
      impIC φ (fun env' => extract D ρ env') env
  | _, _, .impE D₁ D₂, ρ, env => impEC (extract D₁ ρ env) (extract D₂ ρ env)
  | _, _, .botE _, _, _ => botEC
  | _, _, @Deriv.allI _ y _ D _, ρ, env =>
      allIC (fun k => extract D (Function.update ρ y k) env)
  | _, _, .allE u D _, ρ, env => allEC (extract D ρ env) (u.eval ρ)
  | _, _, .ind D₁ D₂ _, ρ, env => indC (extract D₁ ρ env) (extract D₂ ρ env)
  | _, _, .eqDec s t, ρ, _ => eqDecC (decide (s.eval ρ = t.eval ρ))
  | _, _, .succNeZero _, _, _ => axiomC
  | _, _, .succInj _ _, _, _ => axiomC
  | _, _, .eqRefl _, _, _ => axiomC
  | _, _, .eqSymm _ _, _, _ => axiomC
  | _, _, .eqTrans _ _ _, _, _ => axiomC
  | _, _, .eqCongSucc _ _, _, _ => axiomC
  | _, _, .eqCongPlus _ _ _ _, _, _ => axiomC
  | _, _, .eqCongTimes _ _ _ _, _, _ => axiomC
  | _, _, .zeroPlus _, _, _ => axiomC
  | _, _, .succPlus _ _, _, _ => axiomC
  | _, _, .zeroTimes _, _, _ => axiomC
  | _, _, .succTimes _ _, _, _ => axiomC
  | _, _, .predZero, _, _ => axiomC
  | _, _, .predSucc _, _, _ => axiomC
  | _, _, .expZero _, _, _ => axiomC
  | _, _, .expSucc _ _, _, _ => axiomC
  | _, _, .bumpZero _, _, _ => axiomC
  | _, _, .bumpNum _ _, _, _ => axiomC
  | _, _, .goodZero _, _, _ => axiomC
  | _, _, .goodSucc _ _, _, _ => axiomC
  | _, _, .eqCongPred _ _, _, _ => axiomC
  | _, _, .eqCongExp _ _ _ _, _, _ => axiomC
  | _, _, .eqCongBump _ _ _ _, _, _ => axiomC
  | _, _, .eqCongGood _ _ _ _, _, _ => axiomC

/-- The ambient level above which a derivation's extracted family
realizes its conclusion. -/
def derivBound : {Γ : List Formula} → {φ : Formula} → Deriv Γ φ → ℕ
  | _, _, @Deriv.ax _ φ => lvl φ
  | _, _, .wk D => derivBound D
  | _, _, .andI D₁ D₂ => max (derivBound D₁) (derivBound D₂)
  | _, _, .andE₁ D => derivBound D
  | _, _, .andE₂ D => derivBound D
  | _, _, .orI₁ D => derivBound D
  | _, _, .orI₂ D => derivBound D
  | _, _, @Deriv.orE _ φ ψ _ D D₁ D₂ =>
      max (max (derivBound D) (max (lvl φ) (lvl ψ)))
        (max (derivBound D₁) (derivBound D₂))
  | _, _, @Deriv.impI _ φ _ D => max (derivBound D) (lvl φ) + 1
  | _, _, .impE D₁ D₂ => max (derivBound D₁) (derivBound D₂)
  | _, _, .botE D => derivBound D
  | _, _, .allI D _ => derivBound D + 1
  | _, _, .allE _ D _ => derivBound D
  | _, _, .ind D₁ D₂ _ => max (derivBound D₁) (derivBound D₂) + 1
  | _, _, .eqDec _ _ => 1
  | _, _, .succNeZero _ => 1
  | _, _, .succInj _ _ => 1
  -- Phase A: bare equations are realized at every ambient (bound 0);
  -- single implications need one binder level, nested ones two.
  | _, _, .eqRefl _ => 0
  | _, _, .eqSymm _ _ => 1
  | _, _, .eqTrans _ _ _ => 2
  | _, _, .eqCongSucc _ _ => 1
  | _, _, .eqCongPlus _ _ _ _ => 2
  | _, _, .eqCongTimes _ _ _ _ => 2
  | _, _, .zeroPlus _ => 0
  | _, _, .succPlus _ _ => 0
  | _, _, .zeroTimes _ => 0
  | _, _, .succTimes _ _ => 0
  | _, _, .predZero => 0
  | _, _, .predSucc _ => 0
  | _, _, .expZero _ => 0
  | _, _, .expSucc _ _ => 0
  | _, _, .bumpZero _ => 0
  | _, _, .bumpNum _ _ => 0
  | _, _, .goodZero _ => 0
  | _, _, .goodSucc _ _ => 0
  | _, _, .eqCongPred _ _ => 1
  | _, _, .eqCongExp _ _ _ _ => 2
  | _, _, .eqCongBump _ _ _ _ => 2
  | _, _, .eqCongGood _ _ _ _ => 2

end Realizability
