/-
# Extraction: a realizing term for each derivation rule

Extraction recurses on the derivation, carrying the context as a list of
ambient-indexed realizer *families* (`Fam`); the transports of
`Transport.lean` turn each binder's single-ambient realizer into such a
family (`famOf`), which is what closes the ambient-mismatch gap
identified in STATUS.md.

Every rule has its own named combinator, listed in STATUS.md:

* `axC`, and tail-recursion for `wk`;
* `andIC`, `andE₁C`, `andE₂C` — pointwise pairing and projections;
* `orI₁C`, `orI₂C` — tagging; `orEC` — pointwise tag-split, rebuilding
  the hypothesis family from the payload at each ambient (so no
  cross-ambient tag-coherence invariant is ever needed);
* `impIC` — abstraction over the family of the bound realizer;
  `impEC` — application one ambient up;
* `botEC` — vacuous; `allIC` — abstraction reading the numeral from the
  argument; `allEC` — application at the numeral of the term's value;
* `indC` — the induction recursor: the type-indexed primitive recursion
  `indRecC` (the number of `app₁` steps is the numeral being realized),
  packaged by `allIC`;
* `tiC` — the transfinite recursor (Phase C): `tiRecC`, recursion along
  the notation order `≺` of `Epsilon0.lean` rather than along `succ`,
  likewise packaged by `allIC`.  These two are the only combinators that
  recurse;
* `eqDecC` — the decidable-equality tag; `axiomC` — the (contentless)
  realizer of the two successor axioms and of every later schema.

`derivBound` assigns each derivation the ambient level above which its
extracted family realizes the conclusion (`Soundness.lean`).
-/
import Realizability.Transport

namespace Realizability

open ContinuousFunctionals

/-- Ambient-indexed realizer families. -/
def Fam : Type :=
  (n : ℕ) → PureType (n + 1)

/-- The junk family (never consulted where it matters). -/
def defaultFam : Fam :=
  fun n => defaultPT (n + 1)

/-- Context realization: each hypothesis' family realizes it above its
formula's level. -/
def CtxR (ρ : ℕ → ℕ) : List Formula → List Fam → Prop
  | [], _ => True
  | φ :: Γ, env => FR ρ φ (env.headD defaultFam) ∧ CtxR ρ Γ env.tail

/-! ## The named combinators, one per rule -/

/-- `ax`: project the head hypothesis. -/
def axC (env : List Fam) : Fam :=
  env.headD defaultFam

/-- `andI`: pointwise pairing. -/
def andIC (f g : Fam) : Fam :=
  fun n => pairPT (f n) (g n)

/-- `andE₁`: pointwise first projection. -/
def andE₁C (f : Fam) : Fam :=
  fun n => fstPT (f n)

/-- `andE₂`: pointwise second projection. -/
def andE₂C (f : Fam) : Fam :=
  fun n => sndPT (f n)

/-- `orI₁`: tag `0`. -/
def orI₁C (f : Fam) : Fam :=
  fun n => pairPT (fun _ => (0 : ℕ)) (f n)

/-- `orI₂`: tag `1`. -/
def orI₂C (f : Fam) : Fam :=
  fun n => pairPT (fun _ => (1 : ℕ)) (f n)

/-- `orE`: pointwise tag-split on the major premise; each branch rebuilds
its hypothesis family from the payload at the current ambient. -/
def orEC (φ ψ : Formula) (d : Fam)
    (b₁ b₂ : Fam → Fam) : Fam :=
  fun n =>
    if fstPT (d n) (defaultPT n) = 0 then
      b₁ (famOf φ (sndPT (d n))) n
    else
      b₂ (famOf ψ (sndPT (d n))) n

/-- `impI`: abstraction over the family generated by the bound
realizer. -/
def impIC (φ : Formula) (body : List Fam → Fam)
    (env : List Fam) : Fam :=
  fun n =>
    match n with
    | 0 => defaultPT 1
    | m + 1 => abs₁ (fun x => body (famOf φ x :: env) m)

/-- `impE`: application, major premise one ambient up. -/
def impEC (f g : Fam) : Fam :=
  fun n => app₁ (f (n + 1)) (g n)

/-- `botE`: vacuous. -/
def botEC : Fam :=
  defaultFam

/-- `allI`: abstraction reading the numeral off the argument. -/
def allIC (bodyAt : ℕ → Fam) : Fam :=
  fun n =>
    match n with
    | 0 => defaultPT 1
    | m + 1 => abs₁ (fun z => bodyAt (z (defaultPT m)) m)

/-- `allE`: application at the numeral of the term's value. -/
def allEC (f : Fam) (k : ℕ) : Fam :=
  fun n => app₁ (f (n + 1)) (natPT (n + 1) k)

/-- **The type-indexed primitive recursor at a fixed ambient `m`**
(rule `ind`): from the base realizer `a` and the step functional `b` —
the step family's ambient-`(m + 2)` member, whose `∀` clause consumes a
numeral and whose `→` clause then consumes an ambient-`m` realizer —
iterate `app₁` along the numeral:

    indRecC a b 0       = a
    indRecC a b (k + 1) = app₁ (app₁ b (natPT (m + 2) k)) (indRecC a b k)

Unlike every other combinator in this file, this one *iterates*: the
number of applications performed is the numeral being realized.  It is
genuine primitive recursion at the realizer's own type
`PureType (m + 1)` (the `Nat.rec` motive is the pure type, not `ℕ`),
stated once uniformly in the ambient `m` per the level-free-core
discipline — the ambient never changes during the iteration, because
`MR`'s `→` clause consumes and produces at the same level.  Correctness
is `MR_indRecC` in `Soundness.lean`. -/
def indRecC {m : ℕ} (a : PureType (m + 1))
    (b : PureType (m + 3)) : ℕ → PureType (m + 1)
  | 0 => a
  | k + 1 => app₁ (app₁ b (natPT (m + 2) k)) (indRecC a b k)

/-- `ind`: the recursor family — combinator 17.  At each numeral `k`
the ambient-indexed family `m ↦ indRecC (a m) (b (m + 2)) k`, packaged
by `allIC` exactly as `∀`-introduction packages its uniform families:
the concluded formula has the same `∀x. φ` shape, so the same packaging
(abstraction reading the numeral off the argument) applies verbatim. -/
def indC (a b : Fam) : Fam :=
  allIC fun k => fun m => indRecC (a m) (b (m + 2)) k

/-- **The transfinite recursor at a fixed ambient** (rule `tiEps0`) —
combinator 40, and the second combinator that recurses (the first being
`indRecC`).  Where `indRecC` iterates `app₁` along a numeral's successor
structure, this one recurses along the notation order `≺`
(`Epsilon0.lean`):

    tiRecC φ b k = app₁ (app₁ b k̂) ⟨the progressiveness argument at k⟩

and the progressiveness argument, when handed a notation `j` and *any*
realizer of `j ≺ k` (an equation, hence contentless), returns the
recursive value at `j`.  Two `dropR φ` transports appear because the
premise's nested `∀→` consumes its `φ(y)` realizers two ambient levels
below the one the recursion runs at — the level bookkeeping that `ind`
escaped (its step formula has no nested binder pair).

`WellFounded.fix` on `oLt_wf` is used here, and only here.  Two things
make that unproblematic: this combinator is `noncomputable` and never
asked to reduce in the kernel (unlike the Phase-B value functions), and
`Epsilon0.lean` proves `oLt_wf` without `Classical`, so the continuity
theorems' axiom budget is unaffected.  `tiRecC_eq` below is the
non-dependent restatement used by both `MR_tiRecC` (`Soundness.lean`)
and `tiC_tracked` (`GenericContinuity.lean`). -/
def tiRecC (φ : Formula) {m₂ : ℕ} (b : PureType (m₂ + 5)) :
    ℕ → PureType (m₂ + 3) :=
  oLt_wf.fix fun k rec =>
    app₁ (app₁ b (natPT (m₂ + 4) k))
      (abs₁ fun ζ => abs₁ fun _w =>
        if h : OLt (ζ (defaultPT (m₂ + 1))) k then
          dropR φ (dropR φ (rec (ζ (defaultPT (m₂ + 1))) h))
        else defaultPT (m₂ + 1))

/-- One unfolding of the recursor, with the recursive call in
non-dependent form (the accessibility argument is not used in the body,
so `WellFounded.fix_eq` plus `dite_eq_ite` removes it). -/
theorem tiRecC_eq (φ : Formula) {m₂ : ℕ} (b : PureType (m₂ + 5)) (k : ℕ) :
    tiRecC φ b k =
      app₁ (app₁ b (natPT (m₂ + 4) k))
        (abs₁ fun ζ => abs₁ fun _w =>
          if OLt (ζ (defaultPT (m₂ + 1))) k then
            dropR φ (dropR φ (tiRecC φ b (ζ (defaultPT (m₂ + 1)))))
          else defaultPT (m₂ + 1)) := by
  conv_lhs => rw [tiRecC, WellFounded.fix_eq]
  simp only [dite_eq_ite]
  rfl

/-! ## Memoized evaluation of the transfinite recursor (Phase D6)

Phase D4 measured the extracted program's cost and found it is *not*
redundant work inside any primitive — three `@[csimp]` sharing variants
were proved and measured to change nothing — but repeated evaluation of
**identical recursive calls**: at `m = 1`, 2376 of the recursor's 2377
body entries are at the same notation code `0`, requested over and over.
`csimp` on a primitive cannot collapse those, because it changes what a
function computes and not how often its caller calls it.

What follows is the fix D4 named and declined to attempt: an explicit,
fully verified memo table, threaded as ordinary data rather than hidden
state — dynamic programming as an accumulator.  Nothing existing is
replaced: `tiRecC` keeps its definition and every theorem about it, and
the memo path is connected to it by a proof (`tiRecC_eq_tiRecCFast`)
rather than by an unverified `@[implemented_by]`.

`tiRecCFast_eq` and `memo_ok` are the two obligations: the memoized
evaluator returns exactly what `tiRecC` returns, and the table it builds
contains only correct entries.  Correctness never depends on the bound
`memoBound` or on the fuel — those are speed parameters, and a lookup
that misses simply recomputes.

## It works, and it does not help.  Measured, not assumed.

The two `csimp` lemmas below are deliberately **not attached** as
attributes, so the shipped evaluation path is unchanged.  With them
attached and instrumented, at `m = 1`:

* `MEMOHIT = 2376`, `MEMOMISS = 0` — the table serves *every* one of D4's
  2376 repeated requests for code `0`.  The memo is not merely correct,
  it is completely effective at what it was built for.
* Wall clock, like for like: `goodsteinStopTime 1` in **4693 ms** with
  the memo against **4614 ms** without; `hydraBattleLength 1` 4703 ms
  against 4758 ms.  Both within noise.  `m = 2` still produced no output
  at 600 s.

The reason is visible in `app₁` two screens up: `app₁ F x` is
`fun w => F (pairPT x (up n w))`, a **closure**.  So `tiRecC φ b k`
allocates two closures and does no work — producing the recursor's value
at a code is `O(1)`, and a table that hands back the same closure instead
of rebuilding it saves exactly those two allocations.  The cost is in
*applying* the value: each of the 2376 consumers applies it to its own
argument, and each application runs the progressiveness realizer from
scratch.  Caching a function does not cache its applications.

Collapsing the tree would need a table keyed by `(code, argument)` — and
the arguments are `PureType` values, i.e. functions, with no decidable
equality to key on.  That is a sharper statement of the obstruction than
D4 had: it is not that Lean lacks the state, it is that the repeated work
is function application and there is nothing to key it by.

It also corrects D4's headline proxy: the *entry count* is not a cost
proxy, because an entry is `O(1)`.  See STATUS.md's Phase-D6 section for
the full accounting.

To switch the memo path on, add `@[csimp]` to the two lemmas below. -/

/-- The memo table: notation code ↦ the recursor's value there. -/
def MemoTbl (m₂ : ℕ) : Type := List (ℕ × PureType (m₂ + 3))

/-- Table lookup. -/
def memoFind {m₂ : ℕ} : MemoTbl m₂ → ℕ → Option (PureType (m₂ + 3))
  | [], _ => none
  | (j, v) :: t, k => if j = k then some v else memoFind t k

/-- A private copy of `tiRecC`, definitionally equal to it, used as the
memo path's fallback.

It exists for one reason: `tiRecC`'s compiled implementation is replaced
by the memoized one below, so a fallback that called `tiRecC` would
re-enter the memo path with a fresh table and could not terminate.  This
copy is compiled as written. -/
def tiRecCRaw (φ : Formula) {m₂ : ℕ} (b : PureType (m₂ + 5)) :
    ℕ → PureType (m₂ + 3) :=
  oLt_wf.fix fun k rec =>
    app₁ (app₁ b (natPT (m₂ + 4) k))
      (abs₁ fun ζ => abs₁ fun _w =>
        if h : OLt (ζ (defaultPT (m₂ + 1))) k then
          dropR φ (dropR φ (rec (ζ (defaultPT (m₂ + 1))) h))
        else defaultPT (m₂ + 1))

theorem tiRecCRaw_eq (φ : Formula) {m₂ : ℕ} (b : PureType (m₂ + 5)) (k : ℕ) :
    tiRecCRaw φ b k = tiRecC φ b k := rfl

/-- The value at a code: the table's entry if there is one, else the
honest recursion.  Written as a `match` rather than with `Option.getD`
deliberately — `getD`'s default argument is evaluated eagerly, which
would recompute on every *hit*. -/
def memoVal (φ : Formula) {m₂ : ℕ} (b : PureType (m₂ + 5))
    (tbl : MemoTbl m₂) (j : ℕ) : PureType (m₂ + 3) :=
  match memoFind tbl j with
  | some v => v
  | none => tiRecCRaw φ b j

/-- **The table invariant**: every entry is the value `tiRecC` computes at
that code.  This is what makes a lookup interchangeable with a
computation. -/
def MemoOK (φ : Formula) {m₂ : ℕ} (b : PureType (m₂ + 5))
    (tbl : MemoTbl m₂) : Prop :=
  ∀ j v, memoFind tbl j = some v → v = tiRecC φ b j

theorem memoVal_eq {φ : Formula} {m₂ : ℕ} {b : PureType (m₂ + 5)}
    {tbl : MemoTbl m₂} (h : MemoOK φ b tbl) (j : ℕ) :
    memoVal φ b tbl j = tiRecC φ b j := by
  unfold memoVal
  cases hm : memoFind tbl j with
  | none => exact tiRecCRaw_eq φ b j
  | some v => exact h j v hm

/-- One unfolding of the recursor with the recursive call served from the
table.  This is `tiRecC_eq`'s right-hand side with `tiRecC φ b` replaced
by `memoVal φ b tbl`, and the table is captured by the closure — which is
the whole point: every later application of that closure reads the same
already-computed value instead of recomputing it. -/
def tiBodyWith (φ : Formula) {m₂ : ℕ} (b : PureType (m₂ + 5))
    (tbl : MemoTbl m₂) (k : ℕ) : PureType (m₂ + 3) :=
  app₁ (app₁ b (natPT (m₂ + 4) k))
    (abs₁ fun ζ => abs₁ fun _w =>
      if OLt (ζ (defaultPT (m₂ + 1))) k then
        dropR φ (dropR φ (memoVal φ b tbl (ζ (defaultPT (m₂ + 1)))))
      else defaultPT (m₂ + 1))

theorem tiBodyWith_eq {φ : Formula} {m₂ : ℕ} {b : PureType (m₂ + 5)}
    {tbl : MemoTbl m₂} (h : MemoOK φ b tbl) (k : ℕ) :
    tiBodyWith φ b tbl k = tiRecC φ b k := by
  rw [tiRecC_eq]
  unfold tiBodyWith
  simp only [memoVal_eq h]

/-! The memoized evaluator.  `memoRec fuel k tbl` returns the value at `k`
together with an extended table; before building the closure at `k` it
folds itself over the candidate codes, **threading the table**, so each
code is computed at most once across the whole build.  Candidates are the
codes `≤ B` lying `≺ k`; a code outside that range is simply recomputed,
which costs time and never correctness. -/

def memoRec (φ : Formula) {m₂ : ℕ} (b : PureType (m₂ + 5)) (B : ℕ) :
    ℕ → ℕ → MemoTbl m₂ → PureType (m₂ + 3) × MemoTbl m₂
  | 0, k, tbl => (tiRecCRaw φ b k, tbl)
  | fuel + 1, k, tbl =>
      match memoFind tbl k with
      | some v => (v, tbl)
      | none =>
          let tbl' := (List.range (B + 1)).foldl
            (fun t j => if oltB j k then (memoRec φ b B fuel j t).2 else t) tbl
          let v := tiBodyWith φ b tbl' k
          (v, (k, v) :: tbl')

/-- Seeding preserves the invariant: folding a table-preserving step over
any list of codes preserves it. -/
theorem memoFold_ok {φ : Formula} {m₂ : ℕ} {b : PureType (m₂ + 5)}
    {step : MemoTbl m₂ → ℕ → MemoTbl m₂}
    (hstep : ∀ (t : MemoTbl m₂) (j : ℕ), MemoOK φ b t → MemoOK φ b (step t j)) :
    ∀ (js : List ℕ) (tbl : MemoTbl m₂), MemoOK φ b tbl →
      MemoOK φ b (js.foldl step tbl)
  | [], _, h => h
  | j :: js, tbl, h => memoFold_ok hstep js _ (hstep tbl j h)

/-- **The two obligations, proved together**: the evaluator's primary
output is `tiRecC`'s value, and the table it hands back satisfies the
invariant.  Induction on the fuel; the seeding fold consumes the same
induction hypothesis, which is why both halves are one statement. -/
theorem memo_ok (φ : Formula) {m₂ : ℕ} (b : PureType (m₂ + 5)) (B : ℕ) :
    ∀ (fuel k : ℕ) (tbl : MemoTbl m₂), MemoOK φ b tbl →
      MemoOK φ b (memoRec φ b B fuel k tbl).2
      ∧ (memoRec φ b B fuel k tbl).1 = tiRecC φ b k := by
  intro fuel
  induction fuel with
  | zero => exact fun k tbl h => ⟨h, tiRecCRaw_eq φ b k⟩
  | succ fuel ih =>
    intro k tbl h
    have hstep : ∀ (t : MemoTbl m₂) (j : ℕ), MemoOK φ b t →
        MemoOK φ b ((fun t j => if oltB j k then (memoRec φ b B fuel j t).2 else t) t j) := by
      intro t j ht
      by_cases hj : oltB j k = true
      · simpa [hj] using (ih j t ht).1
      · simpa [hj] using ht
    cases hm : memoFind tbl k with
    | some v =>
      have he : memoRec φ b B (fuel + 1) k tbl = (v, tbl) := by
        simp [memoRec, hm]
      rw [he]
      exact ⟨h, h k v hm⟩
    | none =>
      set tbl' := (List.range (B + 1)).foldl
        (fun t j => if oltB j k then (memoRec φ b B fuel j t).2 else t) tbl with htbl'
      have hseed : MemoOK φ b tbl' := memoFold_ok hstep _ tbl h
      have he : memoRec φ b B (fuel + 1) k tbl
          = (tiBodyWith φ b tbl' k, (k, tiBodyWith φ b tbl' k) :: tbl') := by
        simp [memoRec, hm, htbl']
      rw [he]
      refine ⟨?_, tiBodyWith_eq hseed k⟩
      intro j w hw
      by_cases hjk : k = j
      · subst hjk
        have hv : w = tiBodyWith φ b tbl' k := by
          have h2 : memoFind ((k, tiBodyWith φ b tbl' k) :: tbl') k
              = some (tiBodyWith φ b tbl' k) := by simp [memoFind]
          rw [h2] at hw
          injection hw with h3
          exact h3.symm
        rw [hv]
        exact tiBodyWith_eq hseed k
      · exact hseed j w (by simpa [memoFind, hjk] using hw)

/-- How far the table reaches.  A **speed parameter only** — every theorem
below holds for every value of it.  Chosen from the codes the two
headline derivations actually request: the Goodstein ordinals for
`m ≤ 3` are `0, 1, 2, 3, 9, 10` and the small Hydra ones `0, 1, 2, 3`. -/
def memoBound : ℕ := 32

/-- **The memoized recursor.**  Same value as `tiRecC`, computed with a
table. -/
def tiRecCFast (φ : Formula) {m₂ : ℕ} (b : PureType (m₂ + 5)) (k : ℕ) :
    PureType (m₂ + 3) :=
  (memoRec φ b memoBound (memoBound + 3) k []).1

/-- **The equivalence** — the brief's step 2.  Holds at every code, and
independently of the bound and the fuel. -/
theorem tiRecCFast_eq (φ : Formula) {m₂ : ℕ} (b : PureType (m₂ + 5)) (k : ℕ) :
    tiRecCFast φ b k = tiRecC φ b k := by
  have hnil : MemoOK φ b ([] : MemoTbl m₂) := by
    intro j v hv
    exact absurd hv (by simp [memoFind])
  exact (memo_ok φ b memoBound (memoBound + 3) k [] hnil).2

/-- The switch.  Adding `@[csimp]` here routes compiled evaluation through
the memo table; the definition of `tiRecC` is untouched either way, and
kernel reduction (`rfl`, `decide`) is never affected, since `csimp`
governs only code generation.  Left detached: measured to change nothing
(see the section header). -/
theorem tiRecC_eq_tiRecCFast : @tiRecC = @tiRecCFast := by
  funext φ m₂ b k
  exact (tiRecCFast_eq φ b k).symm

/-- `tiEps0`: the recursor family — combinator 40.  Packaged by `allIC`
exactly as `indC` is: the concluded formula is again `∀x. φ`, so the same
abstraction (read the notation code off the argument) applies.  The two
sub-`lvl φ + 2` ambients are junk, and `derivBound` keeps them
unreachable. -/
def tiFamAt (φ : Formula) (b : Fam) (k : ℕ) : Fam
  | 0 => defaultPT 1
  | 1 => defaultPT 2
  | m₂ + 2 => tiRecC φ (b (m₂ + 4)) k

def tiC (φ : Formula) (b : Fam) : Fam :=
  allIC (tiFamAt φ b)

/-! ### The table one level up, where the repetition actually is

Instrumenting the memoized `tiRecC` showed the recursor's body still
entered exactly 2377 times at `m = 1` — D4's own count, unchanged, with
the fallback never taken.  The reason is that the repeated requests do
not come from *inside* the recursion at all: `tiC` packages the recursor
with `allIC`, whose abstraction re-evaluates `tiFamAt φ b k m` on **every
application of the `∀x φ(x)` realizer**, each time entering `tiRecC` from
the top with a fresh table.  A table threaded inside one call cannot see
the other 2375 calls.

So the table has to be built where it can be shared: *outside* the
`abs₁`, once per ambient, captured by the closure.  `tiCTable` does that,
and `tiCFast` is `tiC` with the lookup in place of the recomputation. -/

/-- Values of the recursor family at the codes `≤ B`, at one ambient.
Built once and captured. -/
def tiCTable (φ : Formula) (b : Fam) (B : ℕ) (m : ℕ) :
    List (ℕ × PureType (m + 1)) :=
  (List.range (B + 1)).map fun k => (k, tiFamAt φ b k m)

/-- Lookup with the honest computation as fallback. -/
def tiCFind {m : ℕ} : List (ℕ × PureType (m + 1)) → ℕ →
    Option (PureType (m + 1))
  | [], _ => none
  | (j, v) :: t, k => if j = k then some v else tiCFind t k

def tiCVal (φ : Formula) (b : Fam) {m : ℕ}
    (tbl : List (ℕ × PureType (m + 1))) (k : ℕ) : PureType (m + 1) :=
  match tiCFind tbl k with
  | some v => v
  | none => tiFamAt φ b k m

/-- Every entry of a table built from `tiFamAt` is the value it stands
for — the invariant, proved rather than assumed. -/
theorem tiCFind_sound (φ : Formula) (b : Fam) (m : ℕ) :
    ∀ (js : List ℕ) (k : ℕ) (v : PureType (m + 1)),
      tiCFind (js.map fun k => (k, tiFamAt φ b k m)) k = some v →
      v = tiFamAt φ b k m
  | [], k, v, h => by simp [tiCFind] at h
  | j :: js, k, v, h => by
    rw [List.map_cons] at h
    by_cases hjk : j = k
    · subst hjk
      simp only [tiCFind, if_pos rfl] at h
      injection h with h'
      exact h'.symm
    · simp only [tiCFind, if_neg hjk] at h
      exact tiCFind_sound φ b m js k v h

theorem tiCVal_eq (φ : Formula) (b : Fam) (B m k : ℕ) :
    tiCVal φ b (tiCTable φ b B m) k = tiFamAt φ b k m := by
  show (match tiCFind (tiCTable φ b B m) k with
        | some v => v
        | none => tiFamAt φ b k m) = tiFamAt φ b k m
  cases hf : tiCFind (tiCTable φ b B m) k with
  | none => rfl
  | some v => exact tiCFind_sound φ b m _ k v hf

/-- `tiC`, evaluated through a table built once per ambient. -/
def tiCFast (φ : Formula) (b : Fam) : Fam :=
  fun n =>
    match n with
    | 0 => defaultPT 1
    | m + 1 =>
        let tbl := tiCTable φ b memoBound m
        abs₁ fun z => tiCVal φ b tbl (z (defaultPT m))

/-- **The equivalence**, at every ambient and every code. -/
theorem tiCFast_eq (φ : Formula) (b : Fam) : tiCFast φ b = tiC φ b := by
  funext n
  cases n with
  | zero => rfl
  | succ m =>
    show (abs₁ fun z => tiCVal φ b (tiCTable φ b memoBound m) (z (defaultPT m)))
      = abs₁ fun z => tiFamAt φ b (z (defaultPT m)) m
    simp only [tiCVal_eq]

/-- The same switch one level up.  `tiCFast` builds its table *outside*
the `abs₁`, so it is shared across every application of the `∀x φ(x)`
realizer — the placement D4's diagnosis pointed at.  Instrumentation
found that abstraction is applied exactly **once** per evaluation
(`TICFAM = 1`), so there was nothing there to share either. -/
theorem tiC_eq_tiCFast : @tiC = @tiCFast := by
  funext φ b
  exact (tiCFast_eq φ b).symm

#print axioms memo_ok
#print axioms tiRecCFast_eq
#print axioms tiCFast_eq
#print axioms tiCFind_sound

/-- `exI`: pair the **witness** with the payload — combinator 43.  This is
`orI₁C`/`orI₂C` with a numeral in place of a constant tag, and it is
deliberately the *same* pairing device (`pairPT`): the realizability
clause for `∃` is the clause for `∨` with the tag generalized from two
values to `ℕ`, so no second pairing mechanism is introduced. -/
def exIC (k : ℕ) (f : Fam) : Fam :=
  fun n => pairPT (natPT (n + 1) k) (f n)

/-- `exE`: read the witness off the major premise, then run the body with
the witness *in the environment* and the payload as the hypothesis
family — combinator 44.  Structurally `orEC` with the two-way tag split
replaced by passing the witness along, so again nothing new: `famOf`
rebuilds the hypothesis family at each ambient exactly as there. -/
def exEC (φ : Formula) (d : Fam) (body : ℕ → Fam → Fam) : Fam :=
  fun n => body (fstPT (d n) (defaultPT n)) (famOf φ (sndPT (d n))) n

/-- `eqDec`: tag by the (meta-level) decision of the equation; the
payloads are contentless. -/
def eqDecC (t : Bool) : Fam :=
  fun n =>
    if t then pairPT (fun _ => (0 : ℕ)) (defaultPT (n + 1))
    else pairPT (fun _ => (1 : ℕ)) (defaultPT (n + 1))

/-- `succNeZero` and `succInj` — and, since Phase A, the equational-logic
schemas and the recursion equations for `+`/`×`: contentless realizers
(their implication clauses are vacuous or carry a true equation). -/
def axiomC : Fam :=
  defaultFam

/-! ## The extraction function -/

/-- **Extraction**: a realizing family for each derivation, by recursion
on the derivation, dispatching to the named combinators. -/
def extract : {Γ : List Formula} → {φ : Formula} →
    Deriv Γ φ → (ℕ → ℕ) → List Fam → Fam
  | _, _, .ax, _, env => axC env
  | _, _, .wk D, ρ, env => extract D ρ env.tail
  | _, _, .andI D₁ D₂, ρ, env => andIC (extract D₁ ρ env) (extract D₂ ρ env)
  | _, _, .andE₁ D, ρ, env => andE₁C (extract D ρ env)
  | _, _, .andE₂ D, ρ, env => andE₂C (extract D ρ env)
  | _, _, .orI₁ D, ρ, env => orI₁C (extract D ρ env)
  | _, _, .orI₂ D, ρ, env => orI₂C (extract D ρ env)
  | _, _, @Deriv.orE _ φ ψ _ D D₁ D₂, ρ, env =>
      orEC φ ψ (extract D ρ env)
        (fun p => extract D₁ ρ (p :: env))
        (fun p => extract D₂ ρ (p :: env))
  | _, _, @Deriv.impI _ φ _ D, ρ, env =>
      impIC φ (fun env' => extract D ρ env') env
  | _, _, .impE D₁ D₂, ρ, env => impEC (extract D₁ ρ env) (extract D₂ ρ env)
  | _, _, .botE _, _, _ => botEC
  | _, _, @Deriv.allI _ y _ D _, ρ, env =>
      allIC (fun k => extract D (Function.update ρ y k) env)
  | _, _, .allE u D _, ρ, env => allEC (extract D ρ env) (u.eval ρ)
  | _, _, .ind D₁ D₂ _, ρ, env => indC (extract D₁ ρ env) (extract D₂ ρ env)
  | _, _, .eqDec s t, ρ, _ => eqDecC (decide (s.eval ρ = t.eval ρ))
  | _, _, .succNeZero _, _, _ => axiomC
  | _, _, .succInj _ _, _, _ => axiomC
  | _, _, .eqRefl _, _, _ => axiomC
  | _, _, .eqSymm _ _, _, _ => axiomC
  | _, _, .eqTrans _ _ _, _, _ => axiomC
  | _, _, .eqCongSucc _ _, _, _ => axiomC
  | _, _, .eqCongPlus _ _ _ _, _, _ => axiomC
  | _, _, .eqCongTimes _ _ _ _, _, _ => axiomC
  | _, _, .zeroPlus _, _, _ => axiomC
  | _, _, .succPlus _ _, _, _ => axiomC
  | _, _, .zeroTimes _, _, _ => axiomC
  | _, _, .succTimes _ _, _, _ => axiomC
  | _, _, .predZero, _, _ => axiomC
  | _, _, .predSucc _, _, _ => axiomC
  | _, _, .expZero _, _, _ => axiomC
  | _, _, .expSucc _ _, _, _ => axiomC
  | _, _, .bumpZero _, _, _ => axiomC
  | _, _, .bumpNum _ _, _, _ => axiomC
  | _, _, .goodZero _, _, _ => axiomC
  | _, _, .goodSucc _ _, _, _ => axiomC
  | _, _, .eqCongPred _ _, _, _ => axiomC
  | _, _, .eqCongExp _ _ _ _, _, _ => axiomC
  | _, _, .eqCongBump _ _ _ _, _, _ => axiomC
  | _, _, .eqCongGood _ _ _ _, _, _ => axiomC
  | _, _, @Deriv.tiEps0 _ _ _ φ D _ _ _, ρ, env => tiC φ (extract D ρ env)
  | _, _, .precNum _ _, _, _ => axiomC
  | _, _, .eqCongPrec _ _ _ _, _, _ => axiomC
  | _, _, .ordBump _ _, _, _ => axiomC
  | _, _, .ordPredLt _ _, _, _ => axiomC
  | _, _, .bumpNeZero _ _, _, _ => axiomC
  | _, _, .eqCongOrd _ _ _ _, _, _ => axiomC
  | _, _, .exI u D _, ρ, env => exIC (u.eval ρ) (extract D ρ env)
  | _, _, @Deriv.exE _ x φ _ D₁ D₂ _ _, ρ, env =>
      exEC φ (extract D₁ ρ env)
        (fun w p => extract D₂ (Function.update ρ x w) (p :: env))
  -- Phase H4: the Hydra schemas are contentless, like every other
  -- equation/implication axiom of the fragment.
  | _, _, .hydraZero _, _, _ => axiomC
  | _, _, .hydraSucc _ _, _, _ => axiomC
  | _, _, .hordCutLt _ _, _, _ => axiomC
  | _, _, .hcutNum _ _, _, _ => axiomC
  | _, _, .eqCongHcut _ _ _ _, _, _ => axiomC
  | _, _, .eqCongHydra _ _ _ _, _, _ => axiomC
  | _, _, .eqCongHord _ _, _, _ => axiomC
  -- Phase E2: the Hanoi schemas are contentless, like every other
  -- equation/implication axiom of the fragment.
  | _, _, .solvesZero _ _ _, _, _ => axiomC
  | _, _, .solvesSucc _ _ _ _ _ _, _, _ => axiomC
  | _, _, .mvcountNil, _, _ => axiomC
  | _, _, .mvcountApp _ _ _, _, _ => axiomC
  | _, _, .eqCongHcons _ _ _ _, _, _ => axiomC
  | _, _, .eqCongHapp _ _ _ _, _, _ => axiomC
  | _, _, .eqCongMvcount _ _, _, _ => axiomC
  | _, _, .eqCongSolves _ _ _ _ _ _ _ _ _ _, _, _ => axiomC
  -- Phase F2: the Pascal schemas, contentless like every other equation
  -- axiom of the fragment.
  | _, _, .pasZeroZero, _, _ => axiomC
  | _, _, .pasZeroSucc _, _, _ => axiomC
  | _, _, .pasSuccZero _, _, _ => axiomC
  | _, _, .pasSuccSucc _ _, _, _ => axiomC
  | _, _, .xorNum _ _, _, _ => axiomC
  | _, _, .eqCongXor _ _ _ _, _, _ => axiomC
  | _, _, .eqCongPas _ _ _ _, _, _ => axiomC
  | _, _, .lookNum _ _, _, _ => axiomC
  | _, _, .eqCongLook _ _ _ _, _, _ => axiomC

/-- **The witness is readable off an `∃`-realizer**: the first component
at the canonical point is the witness the introduction rule supplied.
(`pairPT` goes through `Nat.pair`, whose Mathlib inverse does not reduce
in the kernel, so this is a rewriting step rather than `rfl`.) -/
theorem exIC_witness (k : ℕ) (f : Fam) (n : ℕ) :
    fstPT (exIC k f n) (defaultPT n) = k := by
  show fstPT (pairPT (natPT (n + 1) k) (f n)) (defaultPT n) = k
  rw [fstPT_pairPT]
  rfl

/-- Extraction at `∃`-introduction, as a rewriting rule (elaborating the
unfolding inside the big induction of `GenericContinuity.lean` directly is
needlessly expensive; these two lemmas make it a `rfl`-cheap step). -/
theorem extract_exI {Γ : List Formula} {x : ℕ} {φ : Formula} (u : Term)
    (D : Deriv Γ (φ.subst x u)) (hok : Formula.SubstOK u φ)
    (ρ : ℕ → ℕ) (env : List Fam) :
    extract (.exI u D hok) ρ env = exIC (u.eval ρ) (extract D ρ env) := rfl

/-- Extraction at `∃`-elimination, as a rewriting rule. -/
theorem extract_exE {Γ : List Formula} {x : ℕ} {φ ψ : Formula}
    (D₁ : Deriv Γ (.ex x φ)) (D₂ : Deriv (φ :: Γ) ψ)
    (hfresh : FreshIn x Γ) (hnf : ¬ ψ.FreeIn x)
    (ρ : ℕ → ℕ) (env : List Fam) :
    extract (.exE D₁ D₂ hfresh hnf) ρ env
      = exEC φ (extract D₁ ρ env)
          (fun w p => extract D₂ (Function.update ρ x w) (p :: env)) := rfl

/-- The ambient level above which a derivation's extracted family
realizes its conclusion. -/
def derivBound : {Γ : List Formula} → {φ : Formula} → Deriv Γ φ → ℕ
  | _, _, @Deriv.ax _ φ => lvl φ
  | _, _, .wk D => derivBound D
  | _, _, .andI D₁ D₂ => max (derivBound D₁) (derivBound D₂)
  | _, _, .andE₁ D => derivBound D
  | _, _, .andE₂ D => derivBound D
  | _, _, .orI₁ D => derivBound D
  | _, _, .orI₂ D => derivBound D
  | _, _, @Deriv.orE _ φ ψ _ D D₁ D₂ =>
      max (max (derivBound D) (max (lvl φ) (lvl ψ)))
        (max (derivBound D₁) (derivBound D₂))
  | _, _, @Deriv.impI _ φ _ D => max (derivBound D) (lvl φ) + 1
  | _, _, .impE D₁ D₂ => max (derivBound D₁) (derivBound D₂)
  | _, _, .botE D => derivBound D
  | _, _, .allI D _ => derivBound D + 1
  | _, _, .allE _ D _ => derivBound D
  | _, _, .ind D₁ D₂ _ => max (derivBound D₁) (derivBound D₂) + 1
  | _, _, .eqDec _ _ => 1
  | _, _, .succNeZero _ => 1
  | _, _, .succInj _ _ => 1
  -- Phase A: bare equations are realized at every ambient (bound 0);
  -- single implications need one binder level, nested ones two.
  | _, _, .eqRefl _ => 0
  | _, _, .eqSymm _ _ => 1
  | _, _, .eqTrans _ _ _ => 2
  | _, _, .eqCongSucc _ _ => 1
  | _, _, .eqCongPlus _ _ _ _ => 2
  | _, _, .eqCongTimes _ _ _ _ => 2
  | _, _, .zeroPlus _ => 0
  | _, _, .succPlus _ _ => 0
  | _, _, .zeroTimes _ => 0
  | _, _, .succTimes _ _ => 0
  | _, _, .predZero => 0
  | _, _, .predSucc _ => 0
  | _, _, .expZero _ => 0
  | _, _, .expSucc _ _ => 0
  | _, _, .bumpZero _ => 0
  | _, _, .bumpNum _ _ => 0
  | _, _, .goodZero _ => 0
  | _, _, .goodSucc _ _ => 0
  | _, _, .eqCongPred _ _ => 1
  | _, _, .eqCongExp _ _ _ _ => 2
  | _, _, .eqCongBump _ _ _ _ => 2
  | _, _, .eqCongGood _ _ _ _ => 2
  -- Phase C: the recursor needs two ambient levels above the formula's
  -- own for its two `dropR` transports, plus one for the `∀` packaging.
  | _, _, @Deriv.tiEps0 _ _ _ φ D _ _ _ => max (derivBound D) (lvl φ + 2) + 1
  | _, _, .precNum _ _ => 0
  | _, _, .eqCongPrec _ _ _ _ => 2
  -- Phase D0: `∃` costs no ambient level of its own (its clause packages
  -- rather than consumes), so the bounds are `∨`'s.
  | _, _, .ordBump _ _ => 0
  | _, _, .ordPredLt _ _ => 2
  | _, _, .bumpNeZero _ _ => 2
  | _, _, .eqCongOrd _ _ _ _ => 2
  | _, _, .exI _ D _ => derivBound D
  | _, _, @Deriv.exE _ _ φ _ D₁ D₂ _ _ =>
      max (max (derivBound D₁) (lvl φ)) (derivBound D₂)
  -- Phase H4: bare equations at every ambient, single implications at one
  -- binder level, nested ones at two — the Phase-A accounting again.
  | _, _, .hydraZero _ => 0
  | _, _, .hydraSucc _ _ => 0
  | _, _, .hordCutLt _ _ => 2
  | _, _, .hcutNum _ _ => 0
  | _, _, .eqCongHcut _ _ _ _ => 2
  | _, _, .eqCongHydra _ _ _ _ => 2
  | _, _, .eqCongHord _ _ => 1
  -- Phase E2: bare equations at every ambient; one binder level per
  -- implication, so the five-fold congruence of `solves` needs five.
  | _, _, .solvesZero _ _ _ => 0
  | _, _, .solvesSucc _ _ _ _ _ _ => 2
  | _, _, .mvcountNil => 0
  | _, _, .mvcountApp _ _ _ => 0
  | _, _, .eqCongHcons _ _ _ _ => 2
  | _, _, .eqCongHapp _ _ _ _ => 2
  | _, _, .eqCongMvcount _ _ => 1
  | _, _, .eqCongSolves _ _ _ _ _ _ _ _ _ _ => 5
  -- Phase F2: bare equations at every ambient; the congruences need one
  -- binder level per implication.
  | _, _, .pasZeroZero => 0
  | _, _, .pasZeroSucc _ => 0
  | _, _, .pasSuccZero _ => 0
  | _, _, .pasSuccSucc _ _ => 0
  | _, _, .xorNum _ _ => 0
  | _, _, .eqCongXor _ _ _ _ => 2
  | _, _, .eqCongPas _ _ _ _ => 2
  | _, _, .lookNum _ _ => 0
  | _, _, .eqCongLook _ _ _ _ => 2

end Realizability
